# Generated by Django 4.2.7 on 2023-11-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('fin_prdt_cd', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fin_co_no', models.CharField(max_length=255)),
                ('dcls_month', models.CharField(max_length=6)),
                ('kor_co_nm', models.CharField(max_length=255)),
                ('fin_prdt_nm', models.CharField(max_length=255)),
                ('join_way', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.IntegerField()),
                ('join_member', models.TextField()),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(null=True)),
                ('dcls_strt_day', models.CharField(max_length=8)),
                ('dcls_end_day', models.CharField(blank=True, max_length=8, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('fin_prdt_cd', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fin_co_no', models.CharField(max_length=255)),
                ('dcls_month', models.CharField(max_length=6)),
                ('kor_co_nm', models.CharField(max_length=255)),
                ('fin_prdt_nm', models.CharField(max_length=255)),
                ('join_way', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.IntegerField()),
                ('join_member', models.TextField()),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(null=True)),
                ('dcls_strt_day', models.CharField(max_length=8)),
                ('dcls_end_day', models.CharField(blank=True, max_length=8, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=20)),
                ('intr_rate_type_nm', models.CharField(max_length=20)),
                ('rsrv_type', models.CharField(max_length=20)),
                ('rsrv_type_nm', models.CharField(max_length=20)),
                ('save_trm', models.CharField(max_length=10)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.saving')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=20)),
                ('intr_rate_type_nm', models.CharField(max_length=20)),
                ('save_trm', models.CharField(max_length=10)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.deposit')),
            ],
        ),
    ]
