# Generated by Django 4.2.7 on 2023-11-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='board_type',
            field=models.CharField(default='free', max_length=50),
            preserve_default=False,
        ),
    ]
