# Generated by Django 4.2.7 on 2023-11-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit_products',
            field=models.ManyToManyField(blank=True, to='products.deposit'),
        ),
        migrations.AddField(
            model_name='user',
            name='saving_products',
            field=models.ManyToManyField(blank=True, to='products.saving'),
        ),
    ]
